const cards = [
  {
    cardID: 1,
    name: "Info",
    age: 3,
    species: "Dog",
    color: "golden",
    hobby: "run",
    imgURL: "https://via.placeholder.com/200",
    ownerID: 103,
  },
  {
    cardID: 2,
    name: "Info",
    age: 8,
    species: "Cat",
    color: "orange",
    hobby: "scracth",
    imgURL: "https://via.placeholder.com/200",
    ownerID: 102,
  },
  {
    cardID: 3,
    name: "Info",
    age: 1,
    species: "Rabbit",
    color: "white",
    hobby: "Jump",
    imgURL: "https://via.placeholder.com/200",
    ownerID: 101,
  },
  {
    cardID: 4,
    name: "Info",
    age: 5,
    species: "Cat",
    color: "gray",
    hobby: "sleep",
    imgURL: "https://via.placeholder.com/200",
    ownerID: 104,
  },
  {
    cardID: 5,
    name: "Info",
    age: 2,
    species: "Dog",
    color: "brown",
    hobby: "fetch",
    imgURL: "https://via.placeholder.com/200",
    ownerID: 105,
  },
  {
    cardID: 6,
    name: "Info",
    age: 4,
    species: "Rabbit",
    color: "gray",
    hobby: "hop",
    imgURL: "https://via.placeholder.com/200",
    ownerID: 106,
  },
];

export default cards;
